<?php
/**
 * @var Category $category
 * @var Topic $topic
 * @var Comment $comment
 * @var Comment[] $related
 * @var View $this
 */

use App\Util\Html;
use Phalcon\Mvc\View;

?>
<ol class="breadcrumb breadcrumb-dark breadcrumb-transparent">
    <li class="breadcrumb-item">
        <i class="bi-house"></i>
        <a href="<?= $this->url->get(['for' => 'category.list']) ?>">
            Categories
        </a>
    </li>
    <li class="breadcrumb-item">
        <i class="bi-bookshelf"></i>
        <a href="<?= $this->url->get(['for' => 'category.show', 'id' => $category->id]) ?>">
            <?= $category->title ?>
        </a>
    </li>
    <li class="breadcrumb-item">
        <i class="bi-book"></i>
        <a href="<?= $this->url->get(['for' => 'topic.show', 'id' => $topic->id]) ?>">
            <?= $topic->title ?>
        </a>
    </li>
    <li class="breadcrumb-item">
        <i class="bi-chat"></i>
        Comment
    </li>
</ol>

<div class="d-flex align-items-center justify-content-between">
    <h2 class="h4 mt-3 mb-3">
        <i class="bi-book text-tertiary"></i>
        Show comment
    </h2>
    <a class="btn btn-primary" href="<?= $this->url->get(['for' => 'topic.show', 'id' => $topic->id]) ?>">
        <i class="bi-box-arrow-up-right"></i>
        Show parent topic
    </a>
</div>

<div class="card card-body border-0 shadow">
    <div class="lead">
        <?= Html::nl2p($comment->text) ?>
    </div>
    <div class="d-flex align-items-center">
        <div class="text-muted"><?= $comment->created ?></div>
        <a href="<?= $this->url->get(['for' => 'comment.create', 'topic' => $topic->id], ['quoted' => $comment->id]) ?>"
           class="btn btn-sm btn-link ms-4">
            <i class="bi-chat-quote-fill"></i>
            Quote
        </a>
    </div>
</div>

<?php if (!empty($related)): ?>
    <h3 class="h4 text-center mt-3">
        <i class="bi-chat-dots"></i>
        Replies
    </h3>

    <?php foreach ($related as $rComment) {
        $this->partial('comment/_listitem', ['comment' => $rComment, 'quoted' => false]);
    } ?>

<?php endif; ?>
