<?php
/**
 * @var Category $category
 * @var View $this
 * @var stdClass $topics
 * @var User $user
 */

use Phalcon\Mvc\View;

?>
    <nav>
        <ol class="breadcrumb breadcrumb-dark breadcrumb-transparent">
            <li class="breadcrumb-item">
                <i class="bi-house"></i>
                <a href="<?= $this->url->get(['for' => 'category.list']) ?>">
                    Categories
                </a>
            </li>
            <li class="breadcrumb-item">
                <i class="bi-bookshelf"></i>
                <a href="<?= $this->url->get(['for' => 'category.show', 'id' => $category->id]) ?>">
                    <?= $category->title ?>
                </a>
            </li>
        </ol>
    </nav>
    <div class="d-flex align-items-center justify-content-between">
        <h2 class="h4 mt-3 mb-3">
            <i class="bi-bookshelf text-tertiary"></i>
            <?= $category->title ?>
        </h2>
        <div class="text-nowrap">
            <?php if ($user && $this->acl->isAllowed($user->role, Topic::class, 'create')): ?>
                <a class="btn btn-primary text-nowrap btn-sm"
                   href="<?= $this->url->get(['for' => 'topic.create', 'category' => $category->id]) ?>">
                    <i class="bi-plus-lg"></i>
                    New topic
                </a>
            <?php endif; ?>
        </div>
    </div>

<?php if (!$topics->last): ?>
    <div class="h3 text-muted text-center">No topics in this category.</div>
<?php else: ?>
    <div class="card card-body border-0 shadow">
        <?php foreach ($topics->items as $item): ?>
            <div class="mb-3 d-flex justify-content-between text-break">
                <a href="<?= $this->url->get(['for' => 'topic.show', 'id' => $item->id]) ?>">
                    <?= $item->title ?>
                </a>
                <div class="d-flex align-items-baseline ms-1">
                    <div class="text-muted font-monospace font-small text-nowrap">
                        <i class="bi-clock-history"></i>
                        <?= $item->created ?>
                    </div>
                    <?php if ($user && $this->acl->isAllowed($user->role, Topic::class, 'delete', ['topic' => $item])): ?>
                        <a href="<?= $this->url->get(['for' => 'topic.delete', 'id' => $item->id]) ?>"
                           class="btn btn-warning text-nowrap ms-1 btn-sm">
                            <i class="bi-trash-fill"></i>
                            Remove
                        </a>
                    <?php endif; ?>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
<?php endif; ?>
<?php if ($topics->last): ?>
    <div class="mt-3">
        <?php $this->partial('_pagination', ['pager' => $topics, 'url' => ['for' => 'category.show', 'id' => $category->id]]) ?>
    </div>
<?php endif; ?>