<?php
/**
 * @var \Phalcon\Mvc\View $this
 * @var Category[] $catlist
 */
?>
<div class="d-flex justify-content-between align-items-center">
    <div class="h2 mb-0">
        <i class="bi-people-fill"></i>
        Categories
    </div>
    <a href="<?= $this->url->get(['for' => 'admin.category.create']) ?>" class="btn btn-primary">
        <i class="bi-plus"></i>
        New category
    </a>
</div>

<div class="card shadow border-0 mt-3">
    <table class="table table-striped table-hover">
        <thead>
        <tr>
            <td>ID</td>
            <td>Title</td>
            <td>
                <i class="bi-gear-fill"></i>
            </td>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($catlist as $cat): ?>
            <tr>
                <td><?= $cat->id ?></td>
                <td>
                    <a href="<?= $this->url->get(['for' => 'category.show', 'id' => $cat->id]) ?>">
                        <?= $cat->title ?>
                    </a>
                </td>
                <td>
                    <a class="btn btn-danger btn-sm"
                       href="<?= $this->url->get(['for' => 'admin.category.delete', 'id' => $cat->id]) ?>">
                        <i class="bi-trash-fill"></i>
                        Delete
                    </a>
                    <a class="btn btn-primary btn-sm"
                       href="<?= $this->url->get(['for' => 'admin.category.edit', 'id' => $cat->id]) ?>">
                        <i class="bi-pencil-fill"></i>
                        Edit
                    </a>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>