<?php
/**
 * @var stdClass $pager
 * @var string $url
 */
?>
<?php if ($pager->last === 1) {
    return;
} ?>
<ol class="pagination mb-0">
    <?php if ($pager->current != $pager->first): ?>
        <li class="page-item">
            <a class="page-link"
               href="<?= $this->url->get($url, ['page' => $pager->first === $pager->before ? null : $pager->before]) ?>">&laquo;</a>
        </li>
    <?php endif; ?>

    <?php for ($i = 1; $i <= $pager->last; $i++): ?>
        <?php if ($i == $pager->current): ?>
            <li class="page-item active">
                <a class="page-link"><?= $i ?></a>
            </li>
        <?php else: ?>
            <li class="page-item">
                <a class="page-link" href="<?= $this->url->get($url, ['page' => $i === $pager->first ? null : $i]) ?>">
                    <?= $i ?>
                </a>
            </li>
        <?php endif; ?>
    <?php endfor; ?>

    <?php if ($pager->current != $pager->last): ?>
        <li class="page-item">
            <a class="page-link" href="<?= $this->url->get($url, ['page' => $pager->next]) ?>">&raquo;</a>
        </li>
    <?php endif; ?>
</ol>